site_name: 'Coastal Vision Documentation'
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/music-clef-treble
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

nav:
  - 'Home': index.md